obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[-0.305, -0.250], [-0.305, 0.250], [0.305, 0.250], [0.305, -0.250]]
footprint_padding: -0.15
inflation_radius: 0.55
# transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /ebot/laser/scan #scan
  marking: true
  clearing: true

map_type: costmap
