local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base #base_footprint
  update_frequency: 1.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: true
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05 #increase to for higher res 0.025
  # transform_tolerance: 0.5
  cost_scaling_factor: 8
  inflation_radius: 0.25 #was 0.45 before reduced to enable more route.
